apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      name: fe
      labels:
        app: fe
    spec:
      containers:
        - name: fe
          image: huibvstraten/music-release-notifier-fe:0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: coreServiceBaseUrl
              valueFrom:
                configMapKeyRef:
                  name: fe-configmap
                  key: core-service-base-url
            - name: keycloakBaseUrl
              valueFrom:
                configMapKeyRef:
                  name: fe-configmap
                  key: keycloak-base-url

      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: ClusterIP
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80